# yaml-language-server: $schema=https://cloud.dqops.com/dqo-yaml-schema/CheckDefinitionYaml-schema.json
apiVersion: dqo/v1
kind: check
spec:
  sensor_name: column/numeric/non_negative_percent
  rule_name: comparison/max_percent
  help_text: Verifies that the percentage of non-negative values in a column does
    not exceed the maximum accepted percentage. Stores the most recent captured value
    for each day when the data quality check was evaluated.
